### ISSUE TITLE
Documentation update required

### ISSUE THREAD

**Issue by LDong-Arm** [ARMmbed/mbed-os-example-socket-stats#54]
The documentation (README.md) misses the following information
* The `git clone` method does not fetch mbed-os as it's not followed by `mbed deploy`. Maybe it's enough to remove the `git clone` method, as `mbed import` is sufficient.
* It does not tell the user to connect the board using an Ethernet cable.

**Comment by adbridge** [comment]
@evedon who can look at this?

**Comment by ciarmcom** [comment]
Thank you for raising this detailed GitHub issue. I am now notifying our internal issue triagers. 
*Internal Jira reference: https://jira.arm.com/browse/IOTCELL-2458*
