### ISSUE TITLE
Multithreading Issues and Memory Leaks

### ISSUE THREAD

**Issue by nuertey** [ARMmbed/mbed-os-example-socket-stats#7]
Hello @deepikabhavnani ,
Thanks for the example. I was looking at your code and noticed some subtle issues so tried to resolve them in my local copy. I will make a pull request so that if you find any of the changes useful, you can merge them upstream.

I tested my changes on the following compiler/target configuration :

```
Building project mbed-os-example-socket-stats (NUCLEO_F767ZI, GCC_ARM) 
```

Results indicates that it is more stable with the changes and giving more consistent output on the Serial Terminal with both threads reacting more cooperatively now. Ergo :

```
Mbed OS Socket example
Mbed OS version: 5.11.1

IP address: xx.xx.xx.xx
Netmask: xx.xx.xx.xx
Gateway: xx.xx.xx.xx
Num            ID             State          Proto          Sent           Recv           Time           

1              0x2000ea58     Open           TCP            0              0              8232           

1              0x2000e878     Open           UDP            31             0              8232           

2              0x2000ea58     Open           TCP            0              0              8232           

2              0x2000e878     Closed         UDP            31             225            8467           
sent 58 [GET / HTTP/1.1]

3              0x2000ea58     Connected      TCP            58             0              8702           

3              0x2000e878     Closed         UDP            31             225            8467           
recv 180 [HTTP/1.1 200 OK]

4              0x2000ea58     Connected      TCP            58             180            8702           

4              0x2000e878     Closed         UDP            31             225            8467           
External IP address: 174.197.0.234

5              0x2000ea58     Connected      TCP            58             180            8702           

5              0x2000e878     Closed         UDP            31             225            8467           

6              0x2000ea58     Closed         TCP            58             180            9477           

6              0x2000e878     Closed         UDP            31             225            8467           
Done
```

Note that not all my changes might be applicable as I had to blindly "infer" the intent of the particular design of the code from its structure. Some of the minor formatting changes might belong in this category. It just helps me 'read' the code better.
Regards
Nuertey

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBOCUSTRIA-418*

**Comment by nuertey** [comment]
Hi @deepikabhavnani ,
Thinking about things even further, I made a simple change that ensures that the threads exit more gracefully. The nature of threads themselves and the fact that they can and do own resources, and the fact that due to concurrency one is never sure where they might be in their execution stream, makes the case to always prefer joining them rather than terminating them. This way they get to complete their work, and then exit gracefully by releasing any resources that they might own.

I tested it and it works well on my platform. Results are as follows:
```
Mbed OS Socket example
Mbed OS version: 5.11.1

IP address: xx.xx.xx.xx
Netmask: xx.xx.xx.xx
Gateway: xx.xx.xx.xx
Num            ID             State          Proto          Sent           Recv           Time           

1              0x2000ea70     Open           TCP            0              0              5232           

1              0x2000e890     Open           UDP            31             0              5232           

2              0x2000ea70     Open           TCP            0              0              5232           

2              0x2000e890     Closed         UDP            31             225            5467           
sent 58 [GET / HTTP/1.1]

3              0x2000ea70     Connected      TCP            58             0              5702           

3              0x2000e890     Closed         UDP            31             225            5467           
recv 180 [HTTP/1.1 200 OK]

4              0x2000ea70     Connected      TCP            58             180            5702           

4              0x2000e890     Closed         UDP            31             225            5467           
External IP address: 174.197.0.234

5              0x2000ea70     Connected      TCP            58             180            5702           

5              0x2000e890     Closed         UDP            31             225            5467           
Done
```

You will notice that with this new change (which I have updated on the pull request), the last "6 6" output has become superfluous and unnecessary. Immediately the main thread's work is done, the two threads synchronize and everything exits immediately as it should. Hope these changes meet your approval.
Nuertey

**Comment by deepikabhavnani** [comment]
Thanks @nuertey for reporting issue with a solution PR :-) Changes look good to me

> the last "6 6" output has become superfluous and unnecessary

Agree the last print was never needed as all threads exit to socket will close, it was just for verification to make sure close is performed on socket and hence delay equal to sample time was added before thread termination

**Comment by deepikabhavnani** [comment]
Resolved by https://github.com/ARMmbed/mbed-os-example-socket-stats/pull/6
